# -*- coding: utf-8 -*-
"""Clinical_Data_Review_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QQVE_6SHqbPkLr6DfCJn-gDOLOu5hwnW
"""

!pip install faker

import pandas as pd
import numpy as np
from faker import Faker
import random

"""# Clinical Trial Data Review & Query Management System

This project simulates clinical data review workflows used in pharmaceutical clinical trials, including:
- data validation
- query generation
- adverse event review
- data cleaning
- dashboard reporting
"""

#Mock Patients Dataset

fake = Faker()

patients = []

for i in range(1, 101):
    patients.append({
        "Subject_ID": f"SUBJ_{i:03}",
        "Site_ID": random.choice(["SITE_01", "SITE_02", "SITE_03"]),
        "Age": random.randint(18, 85),
        "Sex": random.choice(["M", "F"]),
        "Enrollment_Date": fake.date_between(
            start_date='-1y',
            end_date='today'
        )
    })

patients_df = pd.DataFrame(patients)

patients_df.head()

#Labs Dataset

labs = []

for subject in patients_df["Subject_ID"]:

    hemoglobin = round(random.uniform(8, 18), 1)

    # Introduce missing values intentionally
    if random.random() < 0.1:
        hemoglobin = None

    labs.append({
        "Subject_ID": subject,
        "Visit": random.choice([
            "Screening",
            "Baseline",
            "Week 4"
        ]),
        "Hemoglobin": hemoglobin,
        "WBC": round(random.uniform(3, 12), 1),
        "Platelets": random.randint(100, 450),
        "Lab_Date": fake.date_between(
            start_date='-6m',
            end_date='today'
        )
    })

labs_df = pd.DataFrame(labs)

labs_df.head()

#Adverse Events Dataset

aes = []

for subject in patients_df["Subject_ID"]:

    start_date = fake.date_between(
        start_date='-6m',
        end_date='today'
    )

    aes.append({
        "Subject_ID": subject,
        "AE_Term": random.choice([
            "Headache",
            "Nausea",
            "Fatigue",
            "Anemia"
        ]),
        "Severity": random.choice([
            "Mild",
            "Moderate",
            "Severe",
            None
        ]),
        "Start_Date": start_date,
        "End_Date": fake.date_between(
            start_date=start_date,
            end_date='today'
        )
    })

ae_df = pd.DataFrame(aes)

ae_df.head()

patients_df.to_csv("patients.csv", index=False)
labs_df.to_csv("labs.csv", index=False)
ae_df.to_csv("adverse_events.csv", index=False)

print("Clinical trial datasets saved successfully.")

from google.colab import files

files.download("patients.csv")
files.download("labs.csv")
files.download("adverse_events.csv")

"""# Clinical Data Review & Query Management"""

#Load Datasets

patients_df = pd.read_csv("patients.csv")
labs_df = pd.read_csv("labs.csv")
ae_df = pd.read_csv("adverse_events.csv")

print("Datasets loaded successfully.")

#Empty Query List

queries = []
query_id = 1

#Missing Hemoglobin Check

for index, row in labs_df.iterrows():

    if pd.isnull(row["Hemoglobin"]):

        queries.append({
            "Query_ID": f"Q{query_id:03}",
            "Subject_ID": row["Subject_ID"],
            "Issue": "Missing Hemoglobin Value",
            "Severity": "Medium",
            "Status": "Open"
        })

        query_id += 1

#Invalid Age Check

for index, row in patients_df.iterrows():

    if row["Age"] < 18 or row["Age"] > 85:

        queries.append({
            "Query_ID": f"Q{query_id:03}",
            "Subject_ID": row["Subject_ID"],
            "Issue": "Invalid Age",
            "Severity": "High",
            "Status": "Open"
        })

        query_id += 1

#Missing AE Severity Check

for index, row in ae_df.iterrows():

    if pd.isnull(row["Severity"]):

        queries.append({
            "Query_ID": f"Q{query_id:03}",
            "Subject_ID": row["Subject_ID"],
            "Issue": "Missing AE Severity",
            "Severity": "High",
            "Status": "Open"
        })

        query_id += 1

#Invalid AE Dates Check

ae_df["Start_Date"] = pd.to_datetime(ae_df["Start_Date"])
ae_df["End_Date"] = pd.to_datetime(ae_df["End_Date"])

for index, row in ae_df.iterrows():

    if row["End_Date"] < row["Start_Date"]:

        queries.append({
            "Query_ID": f"Q{query_id:03}",
            "Subject_ID": row["Subject_ID"],
            "Issue": "AE End Date Before Start Date",
            "Severity": "High",
            "Status": "Open"
        })

        query_id += 1

#Query Management Table

queries_df = pd.DataFrame(queries)

queries_df.head(10)

#Query Summary Metrics

print("Total Queries:", len(queries_df))

print("\nQuery Types:")
print(queries_df["Issue"].value_counts())

#Query Report

queries_df.to_csv("clinical_queries.csv", index=False)

print("Clinical query report saved.")

#Download Query Report

from google.colab import files

files.download("clinical_queries.csv")





